myproject/myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
app_name = 'myapp'
urlpatterns = [
    path('', Test.as_view(), name='Test'),
    path('DashboardView/', DashboardView.as_view(), name='DashboardView'),
    path('DashboardColorView/', DashboardColorView.as_view(), name='DashboardColorView'),


    path('BuyerView/', BuyerView.as_view(), name='BuyerView'),
    path('StyleView/', StyleView.as_view(), name='StyleView'),
    path('ProductionLineView/', ProductionLineView.as_view(), name='ProductionLineView'),
    path('OrderQtyView/<int:id>/', OrderQtyView.as_view(), name='OrderQtyView'),
    path('SaveOrderQty/', SaveOrderQty.as_view(), name='SaveOrderQty'),
    path('OrederCMPreportView/', OrederCMPreportView.as_view(), name='OrederCMPreportView'),
    path('OrderQtyDetailView/<int:id>/',OrderQtyDetailView.as_view(), name='OrderQtyDetailView'),
    path('EditOrderQtyView/<int:pk>', EditOrderQtyView.as_view(), name='EditOrderQtyView'),
    path('ETAView/', ETAView.as_view(), name='ETAView'),

    path('ProductionInputView/', ProductionInputView.as_view(), name='ProductionInputView'),
    path('DailyProductionView/', DailyProductionView.as_view(), name='DailyProductionView'),
    path('DailyTargetView/', DailyTargetView.as_view(), name='DailyTargetView'),
    path('DailyTargetFilterView/', DailyTargetFilterView, name='DailyTargetFilterView'),
    path('LineDataEntryView/', LineDataEntryView, name='LineDataEntryView'),
    path('LineDataEntrySave/', LineDataEntrySave.as_view(), name='LineDataEntrySave'),
    path('ProductionLineOutputDetail/', ProductionLineOutputDetail.as_view(), name='ProductionLineOutputDetail'),

    path('DailyAttendanceView/', DailyAttendanceView.as_view(), name='DailyAttendanceView'),

    path('AccInventoyList/', AccInventoyList.as_view(), name='AccInventoyList'),
    path('AccVarientList/', AccVarientList.as_view(), name='AccVarientList'),
    path('create/', ProductCreate.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdate.as_view(), name='update_product'),
    path('delete-image/<int:pk>/', delete_image, name='delete_image'),
    path('delete-variant/<int:pk>/', delete_variant, name='delete_variant'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/templates/AccInventoyList.html
{% extends "base.html" %}


{% block content %}

<div class="row pb-10">

    <div class="col-xl-4 col-lg-4 col-md-6 mb-20">
        <div class="card-box height-100-p widget-style3">
            <div class="d-flex flex-wrap">
                <div class="widget-data">
                    <div class="weight-700 font-24 text-dark"><a href="{% url 'myapp:create_product' %}">Receive_Item</a></div>
                    <div class="font-14 text-secondary weight-500">

                    </div>
                </div>
                <div class="widget-icon">
                    <div class="icon" data-color="#05f511">
                        <i class="icon-copy dw dw-delivery-truck-2"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-6 mb-20">
        <div class="card-box height-100-p widget-style3">
            <div class="d-flex flex-wrap">
                <div class="widget-data">
                    <div class="weight-700 font-24 text-dark"><a href="{% url 'myapp:AccVarientList' %}">Output</a></div>
                    <div class="font-14 text-secondary weight-500">

                    </div>
                </div>
                <div class="widget-icon">
                    <div class="icon" data-color="#eb4034">

                        <i class="icon-copy dw dw-factory"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-6 mb-20">
        <div class="card-box height-100-p widget-style3">
            <div class="d-flex flex-wrap">
                <div class="widget-data">
                    <div class="weight-700 font-24 text-dark"><a href="{% url 'myapp:create_product' %}">Report</a></div>
                    <div class="font-14 text-secondary weight-500">

                    </div>
                </div>
                <div class="widget-icon">
                    <div class="icon" data-color="#05f511">

                        <i class="icon-copy dw dw-profits-1"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Inventory Acc List</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-success">

                <th class="">Buyer</th>
                <th class="">PO#</th>
                                <th class="">Receive Qty</th>
                                <th>Receive Date</th>
                <th class="">Edit</th>
                <th class="">Warehouse</th>




            </tr>
            </thead>
            <tbody>
            {% for a in acc %}
            <tr class="">
                <td class="table-plus"><a href="#"><b>{{a.buyer_name}}</b></a></td>
                <td class="">{{ a.po_style_no }}</td>
                                <td>{{a.receive_qty}}</td>
                <td class=""><a href="#"><b>{{a.sku}}</b></a></td>
                <td class=""><a href="{% url 'myapp:update_product' a.id %}" class="btn btn-sm btn-info"><i class="icon-copy dw dw-edit-file"></i></a></td>
                <td>{{a.warehouse}}</td>



            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

myproject/templates/DailyAttendanceView.html
{% extends 'base.html' %}

{% block content %}



<div class="row clearfix">
    {% for l in line %}
    <!-- Large modal -->
    <div class="col-md-4 col-sm-12 mb-30">
        <div class="pd-20 card-box height-100-p">
            <!--                                <h5 class="h4">Large modal</h5>-->
            <a
                    href="#"
                    class="btn-block"
                    data-toggle="modal"
                    data-target="#bd-example-modal-lg{{l.id}}"
                    type="button"
            >
                <!--                                    <img src="vendors/images/modal-img1.jpg" alt="modal" />-->
                <h4><i class="icon-copy dw dw-scissors"></i>{{l.ProductionLine}}</h4>
            </a>
            <div
                    class="modal fade bs-example-modal-lg"
                    id="bd-example-modal-lg{{l.id}}"
                    tabindex="-1"
                    role="dialog"
                    aria-labelledby="myLargeModalLabel"
                    aria-hidden="true"
            >
                <div class="modal-dialog modal-lg modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myLargeModalLabel">
                                Addendance
                            </h4>
                            <button
                                    type="button"
                                    class="close"
                                    data-dismiss="modal"
                                    aria-hidden="true"
                            >
                                ×
                            </button>
                        </div>
                        <form action="{% url 'myapp:DailyAttendanceView' %}" method="post">{% csrf_token %}
                        <div class="modal-body">
                            <h2 class="text-center">{{l.ProductionLine}}</h2>
                            <input type="text" value="{{l.ProductionLine}}" name="pline" hidden="true">
                            <br>

                            
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-2 col-form-label">Operator</label>
                                <div class="col-sm-12 col-md-8">
                                    <input class="form-control" type="number" placeholder="" name="op">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-2 col-form-label">Helper</label>
                                <div class="col-sm-12 col-md-8">
                                    <input class="form-control" type="number" placeholder="" name="hp">
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button
                                    type="button"
                                    class="btn btn-secondary"
                                    data-dismiss="modal"
                            >
                                Close
                            </button>
                            <button type="submit" class="btn btn-primary">
                                Save changes
                            </button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>







<!--=============================================================-->
<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Daily Attendance List</h4>

    </div>
    <div class="pb-20">
        <table class="table hover data-table">
            <thead>
            <tr class="bg-success">
                
                <th>Line</th>
                <th>Operator</th>
                <th>Helper</th>
                <th>Date</th>

            </tr>
            </thead>
            <tbody>
            {% for p in data %}
            <tr class="">
                                
                <td>{{p.line}}</td>
                <td>{{p.num_operator}}</td>
                <td>{{p.num_helper}}</td>
                <td>{{p.date}}</td>
                


            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>




{% endblock content %}

myproject/templates/DailyProductionView.html
{% extends 'base.html' %}

{% block content %}


<!-- ---------table--------- -->
<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Daily Production</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-primary">

                <th class="">Line Name</th>

                <th class="">InStock</th>
                <th class="">TargetQty</th>
                <th>total output</th>
                <th>
                    %
                </th>


            </tr>
            </thead>
            <tbody>
            {% for p in daily_target_view %}
            <tr class="">
                <td class="table-plus"><a href="{% url 'myapp:LineDataEntryView' %}?pline={{p.line}}"
                                          class="text-primary font-weight-bold d-block"><strong>{{p.line}}</strong></a>
                </td>

                <td>{{p.stock}}</td>
                <td>{{p.daily_target}}</td>
                <td>
                    {{p.t_total_output_qty}}


                </td>
                <td>

                    <script>document.write({{p.t_total_output_qty}}/{{p.sum}}*100);</script>
                    %


                </td>


            </tr>
            {% endfor %}

            </tbody>

        </table>

    </div>

</div>


{% endblock content %}

myproject/templates/DailyTargetView.html
{% extends 'base.html' %}

{% block content %}


<div class="row">

<div class="col-lg-3 col-md-6 col-sm-12 mb-1">
                            <div class="pd-20 card-box height-100-p">
                                <h4 class="mb-20 h4">Production Lines</h4>
                                <div class="list-group">
                                    <a href="{% url 'myapp:DailyTargetView' %}" class="list-group-item list-group-item-action active"><h5>All</h5></a>

                                    {% for i in line %}
                                    <a href="{% url 'myapp:DailyTargetFilterView' %}?pline={{i.ProductionLine}}" class="list-group-item list-group-item-action"><h5>{{i.ProductionLine}}</h5></a>

                                    {% endfor %}
                                    
                                </div>
                            </div>
                        </div>

<!-- ----------------------- -->
<div class="card-box height-100-p col-md-9">
    <br>
    <h3 class="mb-20 h4">Daily Target Production</h3>
<div class="pb-20">

        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-primary">

                <th class="">Line Name</th>
                <th class="">Style</th>
                <th class="">Daily Target Qty</th>
                                <th class="">Status</th>
                <!--                <th>Vou</th>-->


            </tr>
            </thead>
            <tbody>
            {% for p in pro_input %}
            <tr class="">
                <td class="table-plus">{{p.line}}</td>
                <td>
                
                <!-- ------------------------- -->
                <a
                    href="#"
                    class="btn-block text-blue"
                    data-toggle="modal"
                    data-target="#bd-example-modal-lg{{p.id}}"
                    type="button"
            >
               
                <strong>{{p.style}}</strong>
            </a>
            <div
                    class="modal fade bs-example-modal-lg"
                    id="bd-example-modal-lg{{p.id}}"
                    tabindex="-1"
                    role="dialog"
                    aria-labelledby="myLargeModalLabel"
                    aria-hidden="true"
            >
                <div class="modal-dialog modal-lg modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myLargeModalLabel">
                                {{p.line}}
                            </h4>
                           
                            <button
                                    type="button"
                                    class="close"
                                    data-dismiss="modal"
                                    aria-hidden="true"
                            >
                                ×
                            </button>
                        </div>
                        <form action="{% url 'myapp:DailyTargetView' %}" method="post">{% csrf_token %}
                        <div class="modal-body">
                            <h5>Style No - {{p.style}}</h5>
                            <input type="text" value="{{p.line}}" name="line" hidden>
                            <input type="text" value="{{p.style}}" name="style" hidden>
                            <input type="text" value="{{p.input_qty}}" name="input_qty" hidden>
                            <br>

                            
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-2 col-form-label">Daily Target Qty</label>
                                <div class="col-sm-12 col-md-8">
                                    <input class="form-control" type="number" value ="{{p.daily_target}}" name="target_qty">
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button
                                    type="button"
                                    class="btn btn-outline-secondary"
                                    data-dismiss="modal"
                            >
                                Close
                            </button>
                            <button type="submit" class="btn btn-success">
                                Save Target
                            </button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
                <!-- ---------------------- -->
                </td>
                <td>{{p.daily_target}}</td>
                {% if p.status == False %}
                                <td><span class="badge badge-pill badge-warning">pending</span></td>
                {% else %}
                <td><span class="badge badge-pill badge-success">finish</span></td>
                {% endif %}


            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>



</div>

</div>

</div>


<hr>

<div class="card-box mb-30">
    <div class="pd-20">
                <h4 class="text-blue h4"><i class="micon dw dw-karate"></i>-Garment Factory</h4>
        
    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-primary">

                <th class="">Line Name</th>
                <th class="">Style Code</th>
                <th class="">InputQty</th>
                <th class="">TargetQty</th>
                <th>New Order</th>


            </tr>
            </thead>
            <tbody>
            {% for p in daily_target_view %}
            <tr class="">
                <td class="table-plus"><a href="#"><b>{{p.line}}</b></a></td>
                <td>{{p.style}}</td>
                <td>{{p.input_qty}}</td>
                <td>{{p.daily_target}}</td>
                <td>
                    *
                </td>


            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>



{% endblock content %}

myproject/templates/LineDataEntryView.html
{% extends 'base.html' %}

{% block content %}



<div class="row">


{% for i in po %}

<!-- Large modal -->
    <div class="col-md-4 col-sm-12 mb-30">
        <div class="pd-20 card-box height-100-p">
            <!--								<h5 class="h4">Large modal</h5>-->
            <a
                    href="#"
                    class="btn-block"
                    data-toggle="modal"
                    data-target="#bd-example-modal-lg{{i.id}}"
                    type="button"
            >
                <h2 class="text-center">{{i.line}}</h2>
                <hr>
                <h4>Style Code <span class="badge badge-pill badge-warning">#{{i.style}}</span></h4>
                
                
            </a>
            <div
                    class="modal fade bs-example-modal-lg"
                    id="bd-example-modal-lg{{i.id}}"
                    tabindex="-1"
                    role="dialog"
                    aria-labelledby="myLargeModalLabel"
                    aria-hidden="true"
            >
                <div class="modal-dialog modal-lg modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myLargeModalLabel">
                            	Style Code         {{i.style}}
                            </h4>
                            <button
                                    type="button"
                                    class="close"
                                    data-dismiss="modal"
                                    aria-hidden="true"
                            >
                                ×
                            </button>
                        </div>
                        <form action="{% url 'myapp:LineDataEntrySave' %}" method="post">{% csrf_token %}
                        <div class="modal-body">
                        	<input type="" name="id" value="{{i.id}}" hidden>
                        	<input type="" name="style" value="{{i.style}}" hidden>
                        	<input type="" name="cmp_amount" value="{{i.cmp_amount}}" hidden>

                            
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-2 col-form-label">8:30AM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" placeholder="{{i.shift_1}}" name="shift_1" value="{{i.shift_1}}">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">9:30AM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_2}}" name="shift_2">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">10:30AM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_3}}" name="shift_3">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">11:30AM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_4}}" name="shift_4">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">1:00PM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_5}}" name="shift_5">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">2:00PM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_6}}" name="shift_6">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">3:00PM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_7}}" name="shift_7">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">8:30PM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_8}}" name="shift_8">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">4:00PM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_9}}" name="shift_9">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">5:00PM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_10}}" name="shift_10">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">6:00PM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_11}}" name="shift_11">
                                </div>

                                <label class="col-sm-12 col-md-2 col-form-label">7:00PM</label>
                                <div class="col-sm-12 col-md-4">
                                    <input class="form-control" type="number" value="{{i.shift_12}}" name="shift_12">
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button
                                    type="button"
                                    class="btn btn-secondary"
                                    data-dismiss="modal"
                            >
                                Close
                            </button>
                            <button type="submit" class="btn btn-primary">
                                Save changes
                            </button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endfor %}




</div>



{% endblock content %}

myproject/templates/OrderQtyDetailView.html
{% extends 'base.html' %}

{% block content %}


<form>
	<div class="row">
		<div class="col-md-4 col-sm-12">
			<div class="form-group">
				<label>col-md-4</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-4 col-sm-12">
			<div class="form-group">
				<label>col-md-4</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-4 col-sm-12">
			<div class="form-group">
				<label>col-md-4</label>
				<input type="text" class="form-control">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3 col-sm-12">
			<div class="form-group">
				<label>col-md-3</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-3 col-sm-12">
			<div class="form-group">
				<label>col-md-3</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-3 col-sm-12">
			<div class="form-group">
				<label>col-md-3</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-3 col-sm-12">
			<div class="form-group">
				<label>col-md-3</label>
				<input type="text" class="form-control">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-sm-12">
			<div class="form-group">
				<label>col-md-6</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-6 col-sm-12">
			<div class="form-group">
				<label>col-md-6</label>
				<input type="text" class="form-control">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-sm-12">
			<div class="form-group">
				<label>col-md-6</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-3 col-sm-12">
			<div class="form-group">
				<label>col-md-3</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-3 col-sm-12">
			<div class="form-group">
				<label>col-md-3</label>
				<input type="text" class="form-control">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="form-group">
				<label>col-md-12</label>
				<input type="text" class="form-control">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-2 col-sm-12">
			<div class="form-group">
				<label>col-md-2</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-2 col-sm-12">
			<div class="form-group">
				<label>col-md-2</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-2 col-sm-12">
			<div class="form-group">
				<label>col-md-2</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-2 col-sm-12">
			<div class="form-group">
				<label>col-md-2</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-2 col-sm-12">
			<div class="form-group">
				<label>col-md-2</label>
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="col-md-2 col-sm-12">
			<div class="form-group">
				<label>col-md-2</label>
				<input type="text" class="form-control">
			</div>
		</div>
	</div>
</form>



{% endblock content %}

myproject/templates/ProductionLineView.html
{% extends 'base.html' %}

{% block content %}

<div class="page-header">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h5>New Production Line</h5>

            </div>
            <hr>

        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <form action="{% url 'myapp:ProductionLineView' %}" method="post">{% csrf_token %}
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Production Line</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="line">
                    </div>
                </div>


                {% if message %}
                <li class="text-danger">{{message}}</li>

                {% endif %}
                {% if success %}
                <div class="text-success" role="">
                    {{success}}
                </div>
                {% endif %}

                <input type="submit" value="Add Production Line" class="btn btn-primary">


            </form>
        </div>
    </div>
</div>


<!--=============================================================-->
<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Production Line List</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-success">

                <th class="text-center">#</th>
                <th class="text-center">ProductionLine</th>
                <!--                <th class="text-center">More</th>-->
                                <th>Daily Target</th>


            </tr>
            </thead>
            <tbody>
            {% for p in line %}
            <tr class="">
                <td class="table-plus text-center"><a href="#"><b>{{p.id}}</b></a></td>
                <td class="text-center">{{p.ProductionLine}}</td>
                                <td>{{p.daily_target}}</td>


            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

myproject/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% endblock content %}